### PR TITLE
Dot net core

### PR DESCRIPTION
**Pull request by harshjain2**
1. Updated ObjectModel package.
2. Updated check for xunitlibrary in RuntimeLibraries in deps file.
3. Renamed xunit's dotnet test adapter dll name.

### CODE REVIEW

**Comment by harshjain2** [comment]
> Also, is .NET Core discovery going to happen with the Desktop CLR like it does today for all other platforms? Or will it happen with the .NET Core?

.NET Core discovery is going to happen with the .NET Core.

**Comment by harshjain2** [comment]
> Finally, I notice that the .NET Core test adapter is called xunit.runner.visualstudio.testadapter.dll inside the NuGet package. This has historically been the thing that is used for discovery, regardless of the platform for execution, and my concern is that this is going to break older versions of Visual Studio which will try to load this DLL (thinking it's part of the desktop discovery system) and fail.

I've renamed the test adapter to "xunit.runner.visualstudio.dotnetcore.testadapter.dll".

**Comment by harshjain2** [comment]
> Looking at the .nuspec file, this doesn't feel right.

>We ship the runner utility DLL in the .nuspec package because it is part of the runner; however, you've expressed runner.utility as a dependency of the unit test project, which is definitely not how it's done. That DLL needs to live where the runner DLL lives, not where the unit tests live.

I am not able to find a better way to copy the required binaries (runner utility DLL for us) to bin\release folder. Therefore, I've kept it as .nuget package dependency.

@bradwilson : any suggestion for this?

**Comment by bradwilson** [comment]
> @bradwilson : any suggestion for this?

I don't have an answer. It sounds like something in your assembly binding for .NET Core is broken. ☹️

**Comment by harshjain2** [comment]
If we really want to move away from adding nuget reference for xunit.runner.utlity package, we need to either
a.	Run dotnet publish as part of dotnet publish.
b.	Copy the utility dll from packages folder while creating nuget package.

**Comment by bradwilson** [comment]
I'm not sure I understand your options.

> a. Run dotnet publish as part of dotnet publish.

What does `dotnet publish` have to do with anything? We never run this.

> b. Copy the utility dll from packages folder while creating nuget package.

How would this be any different than what we already do for all the other runners?

**Comment by bradwilson** [comment]
(Sorry, accidentally clicked "Close and comment" when I meant just "Comment" :-p)

**Comment by harshjain2** [comment]
>How would this be any different than what we already do for all the other runners?
The only difference is that we need to hard code the version of the utility package in nuspec file and need to update it every time we update the version of utility nuget package.

**Comment by harshjain2** [comment]
>What does dotnet publish have to do with anything? We never run this.

dotnet publish can be used to bring all the dependent dlls (specifically utility dll in our case) to bin\release\publish folder.
After all the depenencies are published, we can pick utility dll and testadapter dll  from this folder while packing them in nuget package.

**Comment by bradwilson** [comment]
Merged into `master`, thanks!

**Pull request closed without merging**
