### PR TITLE
Enable NoAutoReporters in VS test runner

### PR DESCRIPTION
**Pull request by natemcmaster**
Addresses xunit/xunit#1191

cc @bradwilson @onovotny 

image

### CODE REVIEW

**Comment by natemcmaster** [comment]
FYI - part of the reason we want this is the XML reports capture ITestOutputHelper better than TeamCity's autoreporter.

Example: same failure as reporter by two different reporters

Top: TC auto reporter
Bottom: TRX test reporter

https://confluence.jetbrains.com/display/TCD10/XML+Report+Processing
image

**Comment by natemcmaster** [comment]
Ping. When you have a minute, can you take a look @bradwilson or @onovotny  ?

**Comment by bradwilson** [comment]
As an aside: any reason not to just use `dotnet xunit` right now, which already includes this functionality?

**Comment by natemcmaster** [comment]
We might. Adding a DotNetCliToolReference to hundreds of test projects takes some time, and we haven't vetted dotnet-xunit enough yet.

**Comment by natemcmaster** [comment]
Oh, and thanks for merging :)

**Comment by bradwilson** [comment]
`Directory.Build.props`? :)

**Pull request merged**
